# global settings
title: "Harvard AI+HCI Graduate Seminar"
description: "Making computers better collaborators and supporters of human agency"
url: "ai-hci-seminar.seas.harvard.edu" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from
